name: Java TestNG Search CI

on:
  push:
    branches: [ "main", "Test_1" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: TestNG Search Suite
        run: mvn test -DsuiteXmlFile=src/test/java/com/runSignIn.xml

      - name: Check report directory
        run: ls -la target/surefire-reports/

      - name: Upload TestNG report
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: target/surefire-reports/
